[package]
name = "numpy-rust-python"
version = "0.1.0"
edition = "2021"

[dependencies]
numpy-rust-core = { path = "../numpy-rust-core" }
rustpython-vm = { workspace = true }
rustpython-derive = { workspace = true }
crossbeam-utils = "0.8.21"
once_cell = "1.21.3"
